# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerImage',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('img_name', models.CharField(max_length=32, verbose_name='image name')),
                ('upload_time', models.DateTimeField(verbose_name='upload timestamp')),
                ('is_right_estimation', models.BooleanField(default=True, verbose_name='is right estimation')),
                ('recording', models.CharField(max_length=32, verbose_name='tpy of recording')),
                ('damage_grad', models.CharField(max_length=16, verbose_name='damage grade')),
                ('img_file', models.ImageField(upload_to='cust_upload/%Y%m', verbose_name='customer image')),
                ('pred_file', models.ImageField(upload_to='ml_estimated/%Y%m', verbose_name='estimated image')),
                ('cust_img_url', models.CharField(max_length=256, verbose_name='customer upload path')),
                ('ml_img_url', models.CharField(max_length=256, verbose_name='estimated image path')),
            ],
            options={
                'verbose_name': 'customer_image',
                'verbose_name_plural': 'customer_image',
            },
        ),
    ]
