# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerimage',
            options={'verbose_name': 'customer image', 'verbose_name_plural': 'customer image'},
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='damage_grad',
            field=models.CharField(max_length=64, verbose_name='damage grade'),
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id (primary key)'),
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='cust_upload/%Y%m', verbose_name='original image'),
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='img_name',
            field=models.CharField(max_length=64, verbose_name='image name'),
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='is_right_estimation',
            field=models.BooleanField(default=True, verbose_name='verified result'),
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='pred_file',
            field=models.ImageField(blank=True, upload_to='ml_estimated/%Y%m', verbose_name='estimated image'),
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='recording',
            field=models.CharField(max_length=64, verbose_name='type of recording'),
        ),
        migrations.AlterField(
            model_name='customerimage',
            name='username',
            field=models.CharField(max_length=64, verbose_name='username'),
        ),
    ]
